### ISSUE TITLE
Exit status 13

### ISSUE THREAD

**Issue by Kr4utt3r** [FrozenTear7/twitch-spambot#4]
Good Day, 

i tried to run it but i got a weird Error

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\XXxX\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start',
1 verbose cli   'XXxX'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v14.15.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle twitch-spambot@1.1.0~prestart: twitch-spambot@1.1.0
6 info lifecycle twitch-spambot@1.1.0~start: twitch-spambot@1.1.0
7 verbose lifecycle twitch-spambot@1.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle twitch-spambot@1.1.0~start: PATH: C:\Users\XXxX\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\XXxX\Desktop\twitch-spambot-master\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\AdoptOpenJDK\jdk-13.0.2.8-hotspot\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\dotnet\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Topaz Labs LLC\Topaz Video Enhance AI;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Users\XXxX\AppData\Local\Microsoft\WindowsApps;C:\Users\XXxX\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\XXxX\AppData\Local\Programs\Fiddler;C:\Users\XXxX\AppData\Local\Microsoft\WindowsApps;C:\Users\XXxX\AppData\Roaming\npm
9 verbose lifecycle twitch-spambot@1.1.0~start: CWD: C:\Users\XXxX\Desktop\twitch-spambot-master
10 silly lifecycle twitch-spambot@1.1.0~start: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'node --es-module-specifier-resolution=node index.js "XXxX"'
10 silly lifecycle ]
11 silly lifecycle twitch-spambot@1.1.0~start: Returned: code: 13  signal: null
12 info lifecycle twitch-spambot@1.1.0~start: Failed to exec start script
13 verbose stack Error: twitch-spambot@1.1.0 start: `node --es-module-specifier-resolution=node index.js "XXxX"`
13 verbose stack Exit status 13
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\XXxX\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\XXxX\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid twitch-spambot@1.1.0
15 verbose cwd C:\Users\XXxX\Desktop\twitch-spambot-master
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\XXxX\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start" "XXxX"
18 verbose node v14.15.4
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 13
22 error twitch-spambot@1.1.0 start: `node --es-module-specifier-resolution=node index.js "XXxX"`
22 error Exit status 13
23 error Failed at the twitch-spambot@1.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 13, true ]
```

i updated npm and node but nothing changes, can you help me with this?

**Comment by FrozenTear7** [comment]
The error looks almost identical to: https://stackoverflow.com/questions/42308879/how-to-solve-npm-error-npm-err-code-elifecycle.

Basically:
- run `npm cache clean --force`
- delete the `node_modules` directory and `package-lock.json` file
- run `npm install` to install the libraries again

If that doesn't work try other solutions posted on that StackOverflow thread.

**Comment by Kr4utt3r** [comment]
didnt work for me, i followed every solution on StackOverflow.

**Comment by FrozenTear7** [comment]
I tried running it on your version of node.js and everything works fine.
Are you sure you're running the script with `npm start <channel_name>`? I noticed I have to add a better check for args, since when you run just `npm start` it throws an unwanted error and the logs shown are quite similar to the ones you posted here.

Please check the `How to run` section of [README](https://github.com/FrozenTear7/twitch-spambot/blob/master/README.md#how-to-run-the-program) for correct configurations.

**Comment by Kr4utt3r** [comment]
yeah i go into the direction from the spammer and type "npm start Channelname" after that i get the error.


i will create a fresh VM and try it on it

is it important where the login.env is? i have it in the main Folder

**Comment by FrozenTear7** [comment]
`.env` should be located in the main directory.

When you run the script your terminal should like something like this:
```
$ npm start nymn

> twitch-spambot@1.3.0 start
> node --es-module-specifier-resolution=node index.js "nymn"

(node:14236) ExperimentalWarning: The Node.js specifier resolution in ESM is experimental.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14236) ExperimentalWarning: The Node.js specifier resolution in ESM is experimental.
Fetching all global emotes
Finished fetching global emotes
* Connected to irc-ws.chat.twitch.tv:443
* Starting the spambot
```

and if something went wrong, like you provided wrong config, under the second `(node:14236) ExperimentalWarning: The Node.js specifier resolution in ESM is experimental.` warning you should see the message of what failed. Please check that and provide the terminal log beside the logs that you wrote originally.

**Comment by Kr4utt3r** [comment]
You have the 1.3.0 Version and i have the 1.1.0 is there a diffrence because 1.1.0 is the only version i can load.

**Comment by FrozenTear7** [comment]
I'm currently working on a new version, but your version should be working properly. Other than that I don't have any more tips how to fix your problem other than a clean install and maybe running the current version on master instead of the v1.2 release.

**Comment by Kr4utt3r** [comment]
ok i will reinstall Node.js again and try it with the Master, thanks for the help
